### ISSUE TITLE
No visitors showing

### ISSUE THREAD

**Issue by macrobber** [Maaiins/Open-Web-Analytics-VisitorMap#1]
Just installed the module.  Map shows up fine, but there are no visitors being displayed.  Is there a setting in OWA that must be set for this tracking to work correctly?  

No errors in the console. 

Does this require the maxmind_geoip module install?

**Comment by Maaiins** [comment]
You have to add at least geo tracking manually into your code or use maxmind_geoip.

The plugin will not show any "(not set)" locations. The Visitor Geolocation tab has to look like these:
![image](https://user-images.githubusercontent.com/7676540/82733077-bb43a980-9d11-11ea-8019-61249eb9426f.png)
